version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    parameters:
      tag: 2.7
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python -m pytest
          name: Test
  publish-pip:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: verify git tag vs. version
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python setup.py verify
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USER" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create packages
          command: |
            python setup.py sdist
            python setup.py bdist_wheel
      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate
            twine upload dist/*


workflows:
  build_and_deploy:
    jobs:
      - build-and-test
      - publish-pip:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
          context: Production
