version: "3.3"
services:
  landing-zone:
    image: hypernetlabs/landing-zone-daemon
    volumes:
      - source: '\\.\pipe\docker_engine'
        target: '\\.\pipe\docker_engine'
        type: npipe
      - tokens:C:\tokens
      # uncomment the following line if you need to access private image repos with your Landing Zone
      #- C:\$homepath\.docker:C:\Users\ContainerAdministrator\.docker
    container_name: landing-zone-daemon
    # chose the name that appears in the Galileo UI and make a unique string that corresponds to it
    command: --token C:\\tokens\\authfile.txt --name "$LZ_NAME"
volumes:
  tokens:
